[package]
name = "on-coders-mikrotik-noc"
version = "0.5.0"
description = "On Coder's MikroTik NOC — Network Operations Center & RouterOS Monitor Built with Tauri & Vue"
authors = ["Manuel Ron (@Ris3TwO) <manuelron.dev@gmail.com>"]
edition = "2021"
repository = "https://github.com/Ris3TwO/oncoders-mikrotik-noc"
keywords = ["mikrotik", "routeros", "tauri", "noc", "network-monitoring"]
categories = ["network-programming", "gui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "oncoders_mikrotik_noc_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-store = "2.0"
tauri-plugin-updater = "2"
tauri-plugin-dialog = "2.0"
tauri-plugin-process = "2"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4.45"

[profile.release]
codegen-units = 1     # Optimiza todo el binario en una sola unidad (reduce tamaño y mejora velocidad)
lto = true            # Link Time Optimization (elimina código muerto de dependencias de Rust)
opt-level = "s"       # Optimiza estrictamente para reducir el tamaño del binario (puedes usar "z" para tamaño mínimo absoluto)
strip = true          # Elimina todos los símbolos de depuración y metadatos innecesarios

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-window-state = "2"
